### ISSUE TITLE
Issues with realmrelay crypto

### ISSUE THREAD

**Issue by felixtorssell** [tmwilliamlin168/RotMB#1]
I get these errors when I run the program :
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
    The import org.bouncycastle cannot be resolved
    The import org.bouncycastle cannot be resolved
    The import org.bouncycastle cannot be resolved
    StreamCipher cannot be resolved to a type
    StreamCipher cannot be resolved to a type
    RC4Engine cannot be resolved to a type
    KeyParameter cannot be resolved to a type
    KeyParameter cannot be resolved to a type
    StreamCipher cannot be resolved to a type
    StreamCipher cannot be resolved to a type

```
at realmrelay.crypto.RC4.<init>(RC4.java:3)
at realmrelay.User.<init>(User.java:33)
at realmrelay.ROTMGRelay.login(ROTMGRelay.java:151)
at realmrelay.ROTMGRelay.main(ROTMGRelay.java:177)
```

**Comment by tmwilliamlin168** [comment]
Did you add the libraries inside the lib folder?

**Comment by felixtorssell** [comment]
Looks like this: 

https://gyazo.com/a2410822d3acb6e7f16699eafa55dbb4

**Comment by tmwilliamlin168** [comment]
I don't know if this will help... but you are only supposed to have the jar file inside the lib folder.
